--this file call functions to see if transitions correctly
!p1.seeOpponent()
!p1.lostOpponent()
!p1.seeOpponent()
!p1.receiveBlow(50)
!p1.lostOpponent()
!p1.getWeapon(Weapon1)
!p1.seeOpponent()
!p1.landBlow()
!p1.receiveBlow(50)
!p1.seeOpponent()
!p1.lostOpponent()
!p1.receiveBlow(10)
